// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDYQJPOqUl7Oppc1hcrm0qJl1q1_1AW4',
    appId: '1:622543839130:web:de8525149f9f8597b72423',
    messagingSenderId: '622543839130',
    projectId: 'kigali-city-services-37771',
    authDomain: 'kigali-city-services-37771.firebaseapp.com',
    storageBucket: 'kigali-city-services-37771.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChC2mPUC7UNYNps_-FqTWBEFJg6iBddfU',
    appId: '1:622543839130:android:d35b1a75a4942e83b72423',
    messagingSenderId: '622543839130',
    projectId: 'kigali-city-services-37771',
    storageBucket: 'kigali-city-services-37771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-kn3CGx-jZYflC5WizqLKkesFlp8bPqo',
    appId: '1:622543839130:ios:711344f38059c5b6b72423',
    messagingSenderId: '622543839130',
    projectId: 'kigali-city-services-37771',
    storageBucket: 'kigali-city-services-37771.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );
}
